name: Run Gradle on PRs and Pushes
on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: "Setup Java ${{ matrix.os }}"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test createDistributable

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package-${{ matrix.os }}
          path: build/compose/binaries/main/app
