name: Run Gradle on PRs and Pushes
on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # Wait for bug fix: https://github.com/actions/cache/issues/39
      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        if: runner.os != 'Windows'
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        if: runner.os == 'Windows'
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**\build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: run test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package-${{ matrix.os }}
          path: build/distributions
